version: "3.8"

services:

  # MySQL Service
  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mitraruma-api-db
    restart: unless-stopped
    env_file: [.env]
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql